version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - secdevops-network

  snyk:
    image: snyk/snyk
    container_name: snyk
    volumes:
      - .:/project
    entrypoint: ["/bin/sh", "-c"]
    command: ["sh", "-c", "snyk test --all-projects --json"]
    networks:
      - secdevops-network

  owasp-dependency-check:
    image: owasp/dependency-check
    container_name: owasp-dependency-check
    volumes:
      - .:/src
      - ./odc-reports:/report
    entrypoint: ["/bin/sh", "-c"]
    command: ["dependency-check --scan /src --format ALL --out /report"]
    networks:
      - secdevops-network


  LiteratureRecords:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: literatureRecords
    ports:
      - "8082:8082"
    networks:
      - secdevops-network

volumes:
  jenkins_home:

networks:
  secdevops-network:
